TRUNCATE TABLE bikes;
TRUNCATE TABLE dublinmap;
TRUNCATE TABLE gpsbikes;
TRUNCATE TABLE gpsbikes_lastvalid;
TRUNCATE TABLE harvestedbikes;
TRUNCATE TABLE lastdatevisit;
TRUNCATE TABLE mobyarea;
TRUNCATE TABLE rentedbikes;
TRUNCATE TABLE rentedbikes_daily_cumulative;